Repository KB-PJT-15-4/BE, pull requests merged in 2025-07, with the labels that each got.

#1 feat : 프로젝트 setting
  .github/pull_request_template.md
  .gitignore
  .idea/.gitignore
  .idea/dataSources.xml
  .idea/description.html
  .idea/gradle.xml
  .idea/misc.xml
  .idea/project-template.xml
  .idea/sqldialects.xml
  .idea/template-meta.xml
  .idea/vcs.xml
  build.gradle
  database.sql
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/moa/global/config/RootConfig.java
  src/main/java/org/moa/global/config/ServletConfig.java
  src/main/java/org/moa/global/config/WebConfig.java
  src/main/java/org/moa/global/controller/HomeController.java
  src/main/java/org/moa/global/handler/BusinessException.java
  src/main/java/org/moa/global/handler/GlobalExceptionHandler.java
  src/main/java/org/moa/global/mapper/TimeMapper.java
  src/main/java/org/moa/global/response/ApiResponse.java
  src/main/java/org/moa/global/test/controller/UserController.java
  src/main/java/org/moa/global/test/domain/User.java
  src/main/java/org/moa/global/test/domain/UserRequestDto.java
  src/main/java/org/moa/global/test/domain/UserResponseDto.java
  src/main/java/org/moa/global/test/mapper/UserMapper.java
  src/main/java/org/moa/global/test/service/UserService.java
  src/main/java/org/moa/global/type/StatusCode.java
  src/main/resources/log4j2.xml
  src/main/resources/log4jdbc.log4j2.properties
  src/main/resources/mybatis-config.xml
  src/main/resources/org/moa/global.mapper/MapperTemplate.xml
  src/main/resources/org/moa/global/test/mapper/UserMapper.xml
  src/main/webapp/WEB-INF/views/custom404.jsp
  src/main/webapp/WEB-INF/views/error_page.jsp
  src/main/webapp/WEB-INF/views/index.jsp
  src/test/java/org/moa/config/RootConfigTest.java
  src/test/java/org/moa/mapper/TimeMapperTest.java
  src/test/java/org/moa/persistence/JDBCTests.java
Labels: feat, docs, chore

#3 feat:일반 멤버 회원가입 기능 추가
  build.gradle
  src/main/java/org/moa/global/config/RootConfig.java
  src/main/java/org/moa/global/config/ServletConfig.java
  src/main/java/org/moa/global/entity/Account.java
  src/main/java/org/moa/global/handler/GlobalExceptionHandler.java
  src/main/java/org/moa/global/mapper/AccountMapper.java
  src/main/java/org/moa/global/service/account/AccountService.java
  src/main/java/org/moa/global/service/account/AccountServiceImpl.java
  src/main/java/org/moa/global/test/controller/UserController.java
  src/main/java/org/moa/global/test/domain/User.java
  src/main/java/org/moa/global/test/domain/UserRequestDto.java
  src/main/java/org/moa/global/test/domain/UserResponseDto.java
  src/main/java/org/moa/global/test/mapper/UserMapper.java
  src/main/java/org/moa/global/test/service/UserService.java
  src/main/java/org/moa/global/util/HashUtil.java
  src/main/java/org/moa/member/controller/MemberController.java
  src/main/java/org/moa/member/dto/join/MemberJoinRequestDto.java
  src/main/java/org/moa/member/dto/join/OwnerJoinRequestDto.java
  src/main/java/org/moa/member/entity/DriverLicense.java
  src/main/java/org/moa/member/entity/IdCard.java
  src/main/java/org/moa/member/entity/Member.java
  src/main/java/org/moa/member/entity/Owner.java
  src/main/java/org/moa/member/mapper/DriverLicenseMapper.java
  src/main/java/org/moa/member/mapper/IdCardMapper.java
  src/main/java/org/moa/member/mapper/MemberMapper.java
  src/main/java/org/moa/member/service/DriverLicenseService.java
  src/main/java/org/moa/member/service/DriverLicenseServiceImpl.java
  src/main/java/org/moa/member/service/IdCardService.java
  src/main/java/org/moa/member/service/IdCardServiceImpl.java
  src/main/java/org/moa/member/service/MemberService.java
  src/main/java/org/moa/member/service/MemberServiceImpl.java
  src/main/java/org/moa/member/type/Bank.java
  src/main/java/org/moa/member/type/MemberRole.java
  src/main/resources/org/moa/global.mapper/AccountMapper.xml
  src/main/resources/org/moa/global/test/mapper/UserMapper.xml
  src/main/resources/org/moa/member/mapper/DriverLicenseMapper.xml
  src/main/resources/org/moa/member/mapper/IdCardMapper.xml
  src/main/resources/org/moa/member/mapper/MemberMapper.xml
Labels: feat, docs, chore

#10 Feat : 정산 조회하기 기능 구현
  src/main/java/org/moa/trip/controller/TripController.java
  src/main/java/org/moa/trip/dto/expense/ExpenseCreateRequestDto.java
  src/main/java/org/moa/trip/dto/expense/ExpenseResponseDto.java
  src/main/java/org/moa/trip/entity/SettlementNotes.java
  src/main/java/org/moa/trip/mapper/ExpenseMapper.java
  src/main/java/org/moa/trip/mapper/SettlementMapper.java
  src/main/java/org/moa/trip/service/ExpenseService.java
  src/main/java/org/moa/trip/service/ExpenseServiceImpl.java
  src/main/java/org/moa/trip/service/SettlementService.java
  src/main/java/org/moa/trip/service/SettlementServiceImpl.java
  src/main/java/org/moa/trip/service/TripService.java
  src/main/java/org/moa/trip/service/TripServiceImpl.java
  src/main/resources/org/moa/trip/mapper/ExpenseMapper.xml
  src/main/resources/org/moa/trip/mapper/SettlementMApper.xml
  src/test/java/org/moa/trip/service/ExpenseServiceImplTest.java
  src/test/java/org/moa/trip/service/SettlementServiceImplTest.java
Labels: feat

#12 feat: 회원가입 인증 및 회원가입 수정
  src/main/java/org/moa/global/account/mapper/AccountMapper.java
  src/main/java/org/moa/global/security/controller/SecurityController.java
  src/main/java/org/moa/member/controller/MemberController.java
  src/main/java/org/moa/member/dto/verify/MemberVerifyRequestDto.java
  src/main/java/org/moa/member/service/MemberService.java
  src/main/java/org/moa/member/service/MemberServiceImpl.java
  src/main/resources/org/moa/global/account/mapper/AccountMapper.xml
Labels: feat, refactor

#14 feat: CORS 필터 적용
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/org/moa/global/mapper/TimeMapper.java
  src/main/java/org/moa/global/security/config/SecurityConfig.java
  src/main/java/org/moa/global/security/dto/LoginDto.java
  src/main/java/org/moa/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/org/moa/global/security/filter/JwtUsernamePasswordAuthenticationFilter.java
  src/main/resources/org/moa/global.mapper/MapperTemplate.xml
  src/main/resources/org/moa/global/account/mapper/AccountMapper.xml
  src/test/java/org/moa/mapper/TimeMapperTest.java
Labels: feat

#15 feat: QR 코드 생성 및 암/복호화 기능 추가
  .idea/.name
  .idea/dataSources.xml
  build.gradle
  src/main/java/org/moa/global/controller/MemberQrController.java
  src/main/java/org/moa/global/controller/OwnerQrController.java
  src/main/java/org/moa/global/security/filter/AuthenticationErrorFilter.java
  src/main/java/org/moa/global/service/qr/QrService.java
  src/main/java/org/moa/global/service/qr/QrServiceImpl.java
  src/main/java/org/moa/global/util/AesUtil.java
  src/main/java/org/moa/global/util/QrCodeUtil.java
  src/main/java/org/moa/global/util/SecretKeyInitializer.java
  src/main/java/org/moa/member/dto/qr/IdCardResponseDto.java
  src/main/java/org/moa/member/entity/IdCard.java
  src/main/java/org/moa/member/mapper/IdCardMapper.java
  src/main/resources/org/moa/member/mapper/IdCardMapper.xml
  src/main/webapp/favicon.ico
Labels: feat

#16 refactor: 로그인시 암호비교 로직 BCrypt -> 평문
  src/main/java/org/moa/global/security/config/SecurityConfig.java
  src/main/java/org/moa/member/service/MemberServiceImpl.java
Labels: refactor

#24 여행 기록 생성, 일자별 기록 조회 기능 추가
  build.gradle
  src/main/java/org/moa/global/config/ServletConfig.java
  src/main/java/org/moa/trip/controller/TripController.java
  src/main/java/org/moa/trip/controller/TripRecordController.java
  src/main/java/org/moa/trip/dto/record/TripRecordCardDto.java
  src/main/java/org/moa/trip/dto/record/TripRecordRequestDto.java
  src/main/java/org/moa/trip/dto/record/TripRecordResponseDto.java
  src/main/java/org/moa/trip/dto/trip/TripListResponseDto.java
  src/main/java/org/moa/trip/entity/Trip.java
  src/main/java/org/moa/trip/entity/TripRecord.java
  src/main/java/org/moa/trip/entity/TripRecordImage.java
  src/main/java/org/moa/trip/entity/TripRecords.java
  src/main/java/org/moa/trip/entity/TripRecordsImages.java
  src/main/java/org/moa/trip/mapper/TripMapper.java
  src/main/java/org/moa/trip/mapper/TripRecordImageMapper.java
  src/main/java/org/moa/trip/mapper/TripRecordMapper.java
  src/main/java/org/moa/trip/service/TripRecordService.java
  src/main/java/org/moa/trip/service/TripRecordServiceImpl.java
  src/main/resources/org/moa/trip/mapper/TripRecordImageMapper.xml
  src/main/resources/org/moa/trip/mapper/TripRecordMapper.xml
Labels: feat, refactor, chore

#27 여행목록 조회 기능 페이지네이션 방식 변경
  src/main/java/org/moa/trip/controller/TripController.java
  src/main/java/org/moa/trip/dto/trip/PageResponse.java
  src/main/java/org/moa/trip/mapper/TripMapper.java
  src/main/java/org/moa/trip/service/TripService.java
  src/main/java/org/moa/trip/service/TripServiceImpl.java
  src/main/resources/org/moa/trip/mapper/TripMapper.xml
Labels: refactor

#36 Feat: 교통 좌석 예약 확정(결제) 기능
  src/main/java/org/moa/global/account/controller/AccountController.java
  src/main/java/org/moa/reservation/mapper/ReservationMapper.java
  src/main/java/org/moa/reservation/transport/controller/TransportController.java
  src/main/java/org/moa/reservation/transport/dto/TransPaymentRequestDto.java
  src/main/java/org/moa/reservation/transport/mapper/TransportMapper.java
  src/main/java/org/moa/reservation/transport/service/TransportService.java
  src/main/java/org/moa/reservation/transport/service/TransportServiceImpl.java
  src/main/resources/org/moa/reservation/mapper/ReservationMapper.xml
  src/main/resources/org/moa/reservation/transport/mapper/TransportMapper.xml
Labels: feat, docs
