Repository KB-PJT-15-4/BE, pull requests merged in 2025-08, with the labels that each got.

#38 feat: 식당 카테고리 조회 API 구현
  src/main/java/org/moa/reservation/restaurant/controller/CategoryController.java
  src/main/java/org/moa/reservation/restaurant/dto/CategoryResponseDto.java
  src/main/java/org/moa/reservation/restaurant/service/CategoryService.java
  src/main/java/org/moa/reservation/restaurant/service/CategoryServiceImpl.java
  src/main/java/org/moa/reservation/restaurant/type/Category.java
Labels: feat

#39 Fix : getExpenses memberId 제거, 페이징 적용
  src/main/java/org/moa/reservation/accommodation/mapper/AccomResMapper.java
  src/main/java/org/moa/reservation/accommodation/service/AccommodationServiceImpl.java
  src/main/java/org/moa/trip/controller/TripController.java
  src/main/java/org/moa/trip/dto/settlement/SettlementRequestDto.java
  src/main/java/org/moa/trip/mapper/SettlementMapper.java
  src/main/java/org/moa/trip/service/ExpenseService.java
  src/main/java/org/moa/trip/service/ExpenseServiceImpl.java
  src/main/java/org/moa/trip/service/SettlementServiceImpl.java
  src/main/resources/org/moa/reservation/accommodation/mapper/AccomResMapper.xml
  src/main/resources/org/moa/trip/mapper/SettlementMApper.xml
  src/test/java/org/moa/trip/service/ExpenseServiceImplTest.java
Labels: fix, refactor

#40 feat: 교통 좌석 결제전 취소 기능
  src/main/java/org/moa/reservation/mapper/ReservationMapper.java
  src/main/java/org/moa/reservation/transport/controller/TransportController.java
  src/main/java/org/moa/reservation/transport/dto/TransResCancelRequestDto.java
  src/main/java/org/moa/reservation/transport/dto/TransResRequestDto.java
  src/main/java/org/moa/reservation/transport/dto/TransResStatusDto.java
  src/main/java/org/moa/reservation/transport/dto/TransSeatsInfoResponse.java
  src/main/java/org/moa/reservation/transport/dto/TranstInfoResponse.java
  src/main/java/org/moa/reservation/transport/mapper/TransportMapper.java
  src/main/java/org/moa/reservation/transport/service/TransportService.java
  src/main/java/org/moa/reservation/transport/service/TransportServiceImpl.java
  src/main/resources/org/moa/reservation/mapper/ReservationMapper.xml
  src/main/resources/org/moa/reservation/transport/mapper/TransportMapper.xml
Labels: documentation, feat

#41 fix: 식당 카테고리 조회 API
  src/main/java/org/moa/global/config/RootConfig.java
  src/main/java/org/moa/global/config/ServletConfig.java
  src/main/java/org/moa/reservation/restaurant/controller/CategoryController.java
  src/main/java/org/moa/reservation/restaurant/dto/CategoryResponseDto.java
  src/main/java/org/moa/reservation/restaurant/service/CategoryServiceImpl.java
Labels: fix

#42 Feat : 숙소 예약 구현
  src/main/java/org/moa/global/account/service/AccountServiceImpl.java
  src/main/java/org/moa/global/type/ResKind.java
  src/main/java/org/moa/reservation/accommodation/controller/AccommodationController.java
  src/main/java/org/moa/reservation/accommodation/entity/AccommodationInfo.java
  src/main/java/org/moa/reservation/accommodation/mapper/AccomResMapper.java
  src/main/java/org/moa/reservation/accommodation/service/AccommodationService.java
  src/main/java/org/moa/reservation/accommodation/service/AccommodationServiceImpl.java
  src/main/resources/org/moa/reservation/accommodation/mapper/AccomResMapper.xml
  src/main/resources/org/moa/reservation/accommodation/mapper/AccommodationMapper.xml
Labels: feat

#45 feat: 식당 예약 생성, 식당 예약 내역 조회 API 구현
  .idea/dataSources.xml
  src/main/java/org/moa/reservation/restaurant/controller/RestaurantController.java
  src/main/java/org/moa/reservation/restaurant/dto/AvailableTimeResponseDto.java
  src/main/java/org/moa/reservation/restaurant/dto/RestaurantReservationDetailDto.java
  src/main/java/org/moa/reservation/restaurant/dto/RestaurantReservationInsertDto.java
  src/main/java/org/moa/reservation/restaurant/dto/RestaurantReservationRequestDto.java
  src/main/java/org/moa/reservation/restaurant/dto/RestaurantReservationResponseDto.java
  src/main/java/org/moa/reservation/restaurant/mapper/RestaurantMapper.java
  src/main/java/org/moa/reservation/restaurant/service/RestaurantService.java
  src/main/java/org/moa/reservation/restaurant/service/RestaurantServiceImpl.java
  src/main/resources/org/moa/reservation/restaurant/mapper/RestaurantMapper.xml
Labels: feat

#51 feat: 여행 목록 조회 locationName 파라미터 추가
  src/main/java/org/moa/trip/controller/TripController.java
  src/main/java/org/moa/trip/mapper/TripMapper.java
  src/main/java/org/moa/trip/service/TripService.java
  src/main/java/org/moa/trip/service/TripServiceImpl.java
  src/main/resources/org/moa/trip/mapper/TripMapper.xml
Labels: feat, refactor

#52 feat: 식당 정보 조회 API 구현
  src/main/java/org/moa/reservation/restaurant/controller/RestaurantController.java
  src/main/java/org/moa/reservation/restaurant/dto/RestaurantInfoResponseDto.java
  src/main/java/org/moa/reservation/restaurant/mapper/RestaurantMapper.java
  src/main/java/org/moa/reservation/restaurant/service/RestaurantService.java
  src/main/java/org/moa/reservation/restaurant/service/RestaurantServiceImpl.java
  src/main/resources/org/moa/reservation/restaurant/mapper/RestaurantMapper.xml
Labels: feat

#62 fix: 예약 내역 생성 QR
  src/main/java/org/moa/global/controller/MemberQrController.java
  src/main/java/org/moa/global/service/qr/QrService.java
  src/main/java/org/moa/global/service/qr/QrServiceImpl.java
  src/main/java/org/moa/reservation/dto/QrAccommodationReservationDto.java
  src/main/java/org/moa/reservation/dto/QrRestaurantReservationDto.java
  src/main/java/org/moa/reservation/dto/QrTransportReservationDto.java
  src/main/java/org/moa/reservation/mapper/ReservationMapper.java
  src/main/resources/org/moa/reservation/mapper/ReservationMapper.xml
Labels: fix

#65 Feat : 알림 서비스 구현
  src/main/java/org/moa/global/config/FirebaseConfig.java
  src/main/java/org/moa/global/config/RootConfig.java
  src/main/java/org/moa/global/notification/controller/NotificationController.java
  src/main/java/org/moa/global/notification/dto/FcmTokenRequestDto.java
  src/main/java/org/moa/global/notification/dto/NotificationResponseDto.java
  src/main/java/org/moa/global/notification/dto/SettleNotificationRequestDto.java
  src/main/java/org/moa/global/notification/dto/TripNotificationRequestDto.java
  src/main/java/org/moa/global/notification/entity/Notification.java
  src/main/java/org/moa/global/notification/mapper/NotificationMapper.java
  src/main/java/org/moa/global/notification/service/NotificationService.java
  src/main/java/org/moa/global/notification/service/NotificationServiceImpl.java
  src/main/java/org/moa/global/service/FcmService.java
  src/main/java/org/moa/global/type/NotificationType.java
  src/main/java/org/moa/member/mapper/MemberMapper.java
  src/main/java/org/moa/member/service/MemberService.java
  src/main/java/org/moa/member/service/MemberServiceImpl.java
  src/main/java/org/moa/trip/service/ExpenseServiceImpl.java
  src/main/java/org/moa/trip/service/TripServiceImpl.java
  src/main/resources/org/moa/global/notification/mapper/NotificationMapper.xml
  src/main/resources/org/moa/member/mapper/MemberMapper.xml
  src/main/resources/org/moa/trip/mapper/ExpenseMapper.xml
Labels: feat

#66 fix: 예약내역 반환값에 예약ID 포함
  src/main/java/org/moa/reservation/dto/ReservationItemResponseDto.java
  src/main/resources/org/moa/reservation/accommodation/mapper/AccommodationMapper.xml
  src/main/resources/org/moa/reservation/restaurant/mapper/RestaurantMapper.xml
  src/main/resources/org/moa/reservation/transport/mapper/TransportMapper.xml
Labels: fix

#67 refactor: 사업자 계정 테스트 케이스 추가
  sql_test/database.sql
Labels: documentation, enhancement, docs

#69 Feat : 여행 초대 기능 구현, database.sql 수정
  sql_test/database.sql
  src/main/java/org/moa/trip/controller/TripController.java
  src/main/java/org/moa/trip/dto/trip/AddMemberRequestDto.java
  src/main/java/org/moa/trip/mapper/TripMapper.java
  src/main/java/org/moa/trip/service/TripService.java
  src/main/java/org/moa/trip/service/TripServiceImpl.java
  src/main/resources/org/moa/trip/mapper/TripMapper.xml
Labels: enhancement, feat

#71 Fix : 여행에 사용자 여러명 추가 기능, 해당 멤버가 여행에 있는지 검사 기능 추가
  src/main/java/org/moa/member/controller/MemberController.java
  src/main/java/org/moa/member/service/MemberService.java
  src/main/java/org/moa/member/service/MemberServiceImpl.java
  src/main/java/org/moa/trip/dto/trip/AddMemberRequestDto.java
  src/main/java/org/moa/trip/mapper/TripMemberMapper.java
  src/main/java/org/moa/trip/service/ExpenseServiceImpl.java
  src/main/java/org/moa/trip/service/TripServiceImpl.java
  src/main/resources/org/moa/trip/mapper/TripMemberMapper.xml
Labels: fix, refactor

#70 feat: 사장님 QR 확인 API
  src/main/java/org/moa/global/controller/OwnerQrController.java
  src/main/java/org/moa/global/service/qr/QrService.java
  src/main/java/org/moa/global/service/qr/QrServiceImpl.java
  src/main/java/org/moa/global/util/QrCodeUtil.java
  src/main/java/org/moa/member/mapper/OwnerMapper.java
  src/main/java/org/moa/reservation/mapper/ReservationMapper.java
  src/main/java/org/moa/reservation/restaurant/mapper/RestaurantMapper.java
  src/main/resources/org/moa/member/mapper/OwnerMapper.xml
  src/main/resources/org/moa/reservation/mapper/ReservationMapper.xml
Labels: feat

#90 Refactor: 여행 기록 수정 기능 + SQL 데이터 추가
  sql_test/database.sql
  src/main/java/org/moa/global/service/FirebaseStorageService.java
  src/main/java/org/moa/trip/controller/TripRecordController.java
  src/main/java/org/moa/trip/dto/record/TripRecordDetailResponseDto.java
  src/main/java/org/moa/trip/dto/record/TripRecordUpdateRequestDto.java
  src/main/java/org/moa/trip/mapper/TripRecordImageMapper.java
  src/main/java/org/moa/trip/service/TripRecordService.java
  src/main/java/org/moa/trip/service/TripRecordServiceImpl.java
  src/main/resources/org/moa/trip/mapper/TripRecordImageMapper.xml
Labels: refactor

#91 deploy: sql통합 + QR기능 개선 + 여행기록 개선
  sql_test/database.sql
  src/main/java/org/moa/global/config/RootConfig.java
  src/main/java/org/moa/global/service/FirebaseStorageService.java
  src/main/java/org/moa/global/service/qr/QrServiceImpl.java
  src/main/java/org/moa/global/util/QrCodeUtil.java
  src/main/java/org/moa/reservation/dto/qr/QrAccommodationReservationDto.java
  src/main/java/org/moa/reservation/dto/qr/QrItemResponseDto.java
  src/main/java/org/moa/reservation/dto/qr/QrRestaurantReservationDto.java
  src/main/java/org/moa/reservation/dto/qr/QrTransportReservationDto.java
  src/main/java/org/moa/reservation/dto/qr/TransportSeatResponseDto.java
  src/main/java/org/moa/reservation/dto/qr/UserAccommodationReservationDto.java
  src/main/java/org/moa/reservation/dto/qr/UserRestaurantReservationDto.java
  src/main/java/org/moa/reservation/dto/qr/UserTransportReservationDto.java
  src/main/java/org/moa/reservation/mapper/ReservationMapper.java
  src/main/java/org/moa/trip/controller/TripRecordController.java
  src/main/java/org/moa/trip/dto/record/TripRecordDetailResponseDto.java
  src/main/java/org/moa/trip/dto/record/TripRecordUpdateRequestDto.java
  src/main/java/org/moa/trip/mapper/TripRecordImageMapper.java
  src/main/java/org/moa/trip/service/TripRecordService.java
  src/main/java/org/moa/trip/service/TripRecordServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/org/moa/reservation/mapper/ReservationMapper.xml
  src/main/resources/org/moa/trip/mapper/TripRecordImageMapper.xml
Labels: chore

#95 fix: 식당 예약칸 자동 생성
  src/main/java/org/moa/reservation/restaurant/mapper/RestaurantMapper.java
  src/main/java/org/moa/trip/service/TripServiceImpl.java
  src/main/resources/org/moa/reservation/restaurant/mapper/RestaurantMapper.xml
Labels: fix

#100 chore: 숙박 데이터 대문자 -> 소문자 변환
  sql_test/database.sql
  sql_test/insert_accom_res_aug1_to_aug31.sql
Labels: chore
